// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package record_set

import (
	"context"
	"fmt"
	"sync"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcfg "github.com/aws-controllers-k8s/runtime/pkg/config"
	ackmetrics "github.com/aws-controllers-k8s/runtime/pkg/metrics"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/route53"
	"github.com/go-logr/logr"
	ctrlrt "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	"github.com/aws-controllers-k8s/route53-controller/pkg/batch"
	svcresource "github.com/aws-controllers-k8s/route53-controller/pkg/resource"
)

// resourceManagerFactory produces resourceManager objects. It implements the
// `types.AWSResourceManagerFactory` interface.
type resourceManagerFactory struct {
	sync.RWMutex
	// rmCache contains resource managers for a particular AWS account ID
	rmCache map[string]*resourceManager
	// batchAggregator is the shared batch aggregator for all resource managers.
	// Initialized lazily on first ManagerFor call.
	batchAggregator *batch.Aggregator
	// hostedZoneCache is the shared domain cache for all resource managers.
	hostedZoneCache *batch.HostedZoneCache
}

// ResourcePrototype returns an AWSResource that resource managers produced by
// this factory will handle
func (f *resourceManagerFactory) ResourceDescriptor() acktypes.AWSResourceDescriptor {
	return &resourceDescriptor{}
}

// ManagerFor returns a resource manager object that can manage resources for a
// supplied AWS account
func (f *resourceManagerFactory) ManagerFor(
	cfg ackcfg.Config,
	clientcfg aws.Config,
	log logr.Logger,
	metrics *ackmetrics.Metrics,
	rr acktypes.Reconciler,
	id ackv1alpha1.AWSAccountID,
	region ackv1alpha1.AWSRegion,
	roleARN ackv1alpha1.AWSResourceName,
) (acktypes.AWSResourceManager, error) {
	// We use the account ID, region, and role ARN to uniquely identify a
	// resource manager. This helps us to avoid creating multiple resource
	// managers for the same account/region/roleARN combination.
	rmId := fmt.Sprintf("%s/%s/%s", id, region, roleARN)
	f.RLock()
	rm, found := f.rmCache[rmId]
	f.RUnlock()

	if found {
		return rm, nil
	}

	f.Lock()
	defer f.Unlock()

	// Lazily initialize the shared batch aggregator and cache on first use.
	// All resource managers (even for different accounts/regions) share the
	// same aggregator since batching is per-hostedZoneID.
	if f.batchAggregator == nil {
		sdkClient := svcsdk.NewFromConfig(clientcfg)
		f.hostedZoneCache = batch.NewHostedZoneCache(10*time.Minute, log)
		f.batchAggregator = batch.NewAggregator(
			sdkClient,
			metrics,
			log,
			batch.DefaultConfig(),
		)
	}

	rm, err := newResourceManager(cfg, clientcfg, log, metrics, rr, id, region, f.batchAggregator, f.hostedZoneCache)
	if err != nil {
		return nil, err
	}
	f.rmCache[rmId] = rm
	return rm, nil
}

// IsAdoptable returns true if the resource is able to be adopted
func (f *resourceManagerFactory) IsAdoptable() bool {
	return true
}

// RequeueOnSuccessSeconds returns true if the resource should be requeued after specified seconds
// Default is false which means resource will not be requeued after success.
func (f *resourceManagerFactory) RequeueOnSuccessSeconds() int {
	return 0
}

func newResourceManagerFactory() *resourceManagerFactory {
	return &resourceManagerFactory{
		rmCache: map[string]*resourceManager{},
	}
}

// GetBatchReconciler implements acktypes.BatchReconcilerProvider.
// It returns a batch reconciler that groups RecordSet CRs by hosted zone
// and issues a single ChangeResourceRecordSets call per zone per batch.
func (f *resourceManagerFactory) GetBatchReconciler(mgr ctrlrt.Manager) (reconcile.BatchReconciler, reconcile.BatchConfig) {
	f.Lock()
	defer f.Unlock()

	// Load the default AWS config from the environment (same credentials the
	// controller uses). This ensures the batch reconciler has valid creds.
	// Disable the SDK's client-side retry rate limiter — we handle retries
	// at the batch level and don't want the token bucket blocking us.
	awsCfg, err := awsconfig.LoadDefaultConfig(context.Background(), awsconfig.WithRegion("us-west-2"))
	if err != nil {
		// If we can't load AWS config, skip batch reconciling
		return nil, reconcile.BatchConfig{}
	}

	sdkClient := svcsdk.NewFromConfig(awsCfg, func(o *svcsdk.Options) {
		o.RetryMaxAttempts = 1
	})
	hzCache := batch.NewHostedZoneCache(10*time.Minute, ctrlrt.Log)

	br := NewListDrivenBatchReconciler(
		mgr.GetClient(),
		sdkClient,
		ctrlrt.Log,
		nil,
		hzCache,
	)

	return br, reconcile.BatchConfig{
		MaxBatchSize: 500,
		MaxWait:      2 * time.Second,
	}
}

func init() {
	svcresource.RegisterManagerFactory(newResourceManagerFactory())
}
